# Generated by Django 5.1 on 2025-06-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0003_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
