# Generated by Django 5.1 on 2025-06-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0005_address_address_name_address_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.CharField(default='1', max_length=12),
            preserve_default=False,
        ),
    ]
