# Generated by Django 5.1 on 2025-06-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0006_remove_address_user_address_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
