# Generated by Django 5.1 on 2025-06-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0007_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
