# Generated by Django 5.1 on 2025-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0008_user_alternate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-10 19:37:00'),
            preserve_default=False,
        ),
    ]
