# Generated by Django 5.1 on 2025-06-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plain_text_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
