# Generated by Django 5.1 on 2025-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active_cart',
            field=models.BooleanField(default=True),
        ),
    ]
