# Generated by Django 5.1 on 2025-05-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_category_created_at_subcategory_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
