# Generated by Django 5.1 on 2025-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_availabilitycharges_is_active_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
    ]
