# Generated by Django 5.1 on 2025-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_timeslot_end_time_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.JSONField(default=[]),
        ),
    ]
