# Generated by Django 5.1 on 2025-05-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.JSONField(default=list),
        ),
    ]
