# Generated by Django 5.1 on 2025-06-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_pincode_city_pincode_delivery_charge_pincode_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='delivery_charges',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
