# Generated by Django 5.1 on 2025-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_timeslot_delivery_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='delivery_charge',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
