# Generated by Django 5.1 on 2025-07-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
