# Generated by Django 5.1 on 2025-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
