# Generated by Django 5.1 on 2025-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_product_special_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergen_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
