# Generated by Django 5.1 on 2025-07-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_product_allergen_information_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitycharges',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='availabilitycharges',
            name='product_variation_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_variation_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
