# Generated by Django 5.1 on 2025-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_alter_availabilitycharges_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
