# Generated by Django 5.1 on 2025-07-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_product_sub_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='stock_bull',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='stock_quantity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
