# Generated by Django 5.1 on 2025-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_productvariation_stock_bull_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='stock_toggle',
            field=models.BooleanField(default=True),
        ),
    ]
