# Generated by Django 5.1 on 2025-08-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_productvariation_stock_toggle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='stock_toggle',
            new_name='stock_mode',
        ),
    ]
