# Generated by Django 5.1 on 2025-08-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_rename_stock_toggle_productvariation_stock_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='stock_bull',
            new_name='in_stock_bull',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='stock_mode',
            new_name='stock_toggle_mode',
        ),
    ]
