# Generated by Django 5.1 on 2025-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_rename_stock_bull_productvariation_in_stock_bull_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
