# Generated by Django 5.1 on 2025-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_productvariation_hsn_productvariation_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
