# Generated by Django 5.1 on 2025-08-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_remove_productvariation_hsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_extras',
            field=models.BooleanField(default=False),
        ),
    ]
