# Generated by Django 5.1 on 2025-08-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_product_is_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_extras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_extras',
            field=models.BooleanField(default=False),
        ),
    ]
