# Generated by Django 5.1 on 2025-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_category_is_extras_subcategory_is_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category_id_list',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
