# Generated by Django 5.1 on 2025-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_product_sub_category_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
