# Generated by Django 5.1 on 2025-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
