# Generated by Django 5.1 on 2025-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.CharField(default='18', max_length=255),
        ),
    ]
