# Generated by Django 5.1 on 2025-08-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='base_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
