# Generated by Django 5.1 on 2025-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_rename_payment_id_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
