# Generated by Django 5.1 on 2025-06-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_coupon_code_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
