# Generated by Django 5.1 on 2025-07-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_coupon_code_alter_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_photos',
            field=models.JSONField(default=list),
        ),
    ]
