# Generated by Django 5.1 on 2025-07-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_order_delivery_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
