# Generated by Django 5.1 on 2025-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_order_extra_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
