# Generated by Django 5.1 on 2025-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_order_session_id_alter_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_partner_commission',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
