# Generated by Django 5.1 on 2025-08-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_order_assigned_delivery_partner_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transport_mode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_photos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
