# Generated by Django 5.1 on 2025-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_order_transport_mode_alter_order_delivery_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_corporate',
            field=models.BooleanField(default=False),
        ),
    ]
