# Generated by Django 5.1 on 2025-08-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
