# Generated by Django 5.1 on 2025-09-06 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('order_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(max_length=20)),
                ('product_variation_id', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_note', models.TextField(blank=True, null=True)),
                ('order_item_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
