# Generated by Django 5.1 on 2025-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsection',
            name='category_id',
            field=models.CharField(blank=True, help_text='Category ID for category-based sections', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productsection',
            name='max_products',
            field=models.PositiveIntegerField(default=8, help_text='Maximum number of products to display'),
        ),
        migrations.AddField(
            model_name='productsection',
            name='show_add_to_cart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsection',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsection',
            name='show_rating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsection',
            name='subcategory_id',
            field=models.CharField(blank=True, help_text='Subcategory ID for more specific filtering', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productsectionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-17 22:37'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsection',
            name='section_type',
            field=models.CharField(choices=[('featured', 'Featured Products'), ('bestsellers', 'Best Sellers'), ('new_arrivals', 'New Arrivals'), ('trending', 'Trending Now'), ('category_based', 'Category Based'), ('custom', 'Custom Selection')], default='featured', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productsectionitem',
            unique_together={('section', 'product_id')},
        ),
    ]
