# Generated by Django 5.1 on 2025-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0002_productsection_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
