# Generated by Django 5.1 on 2025-08-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0003_alter_herobanner_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='button_link',
            field=models.CharField(default='/shop/', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='main_image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='logo_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
