# Generated by Django 5.1 on 2025-08-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0004_alter_aboutsection_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
