# Generated by Django 5.1 on 2025-08-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0005_alter_herobanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecategory',
            name='category_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
