# Generated by Django 5.1 on 2025-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0006_alter_homepagecategory_category_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsection',
            name='section_type',
            field=models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('category_based', 'Category Based'), ('custom', 'Custom Selection')], default='featured', max_length=50),
        ),
    ]
